### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by organnoise** [jstenback/inkscape-gcode#1]
Dumb question, but how do you install this plugin?

I'm especially interested in the rs274 option.

**Comment by jstenback** [comment]
https://inkscape.org/en/gallery/%3Dextension/ explains how to install an Inkscape extension, but given how old this one is, I unfortunately no longer know if it works any more :(

**Comment by organnoise** [comment]
Thanks, I followed those instructions but no luck. Maybe it doesn't work anymore
